In [ ]:
import sklearn
sklearn.__version__

'1.6.1'

In [ ]:
! pip install scikit-learn==1.9.0

Collecting scikit-learn==1.9.0
  Downloading scikit_learn-1.9.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.13/dist-packages (from scikit-learn==1.9.0) (2.1.3)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn==1.9.0) (1.16.3)
Requirement already satisfied: joblib>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn==1.9.0) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /usr/local/lib/python3.13/dist-packages (from scikit-learn==1.9.0) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn==1.9.0) (3.6.0)
Downloading scikit_learn-1.9.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 57.6 MB/s eta 0:00:00
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
Successfully installed scikit-learn-1.9.0

In [ ]:
import sklearn
sklearn.__version__

'1.9.0'

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
d = pd.read_csv('/content/drive/MyDrive/ML/phone_addiction_dataset.csv')
d

,Name,Age,Gender,Location,Daily_Usage_Hours,Sleep_Hours,Interllectual_Performance,Social_Interactions,Exercise_Hours,Anxiety_Level,...,Screen_Time_Before_Bed,Phone_Checks_Per_Day,Apps_Used_Daily,Time_on_Social_Media,Time_on_Gaming,Time_on_Education,Phone_Usage_Purpose,Family_Communication,Weekend_Usage_Hours,Addiction_Level
0,Shannon Francis,13,Female,Hansonfort,4.0,6.1,78,5,0.1,10,...,1.4,86,19,3.6,1.7,1.2,Browsing,4,8.7,10.0
1,Scott Rodriguez,17,Female,Theodorefort,5.5,6.5,70,5,0.0,3,...,0.9,96,9,1.1,4.0,1.8,Browsing,2,5.3,10.0
2,Adrian Knox,13,Other,Lindseystad,5.8,5.5,93,8,0.8,2,...,0.5,137,8,0.3,1.5,0.4,Education,6,5.7,9.2
3,Brittany Hamilton,18,Female,West Anthony,3.1,3.9,78,8,1.6,9,...,1.4,128,7,3.1,1.6,0.8,Social Media,8,3.0,9.8
4,Steven Smith,14,Other,Port Lindsaystad,2.5,6.7,56,4,1.1,1,...,1.0,96,20,2.6,0.9,1.1,Gaming,10,3.7,8.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,Jesus Yates,38,Female,New Jennifer,3.9,6.4,53,4,0.9,7,...,0.3,80,15,2.7,1.8,1.0,Other,8,9.4,9.8
5996,Bethany Murray,80,Female,Richardport,3.6,7.3,93,5,0.0,8,...,0.9,45,8,3.1,0.0,0.3,Gaming,9,5.2,5.5
5997,Norman Hughes,21,Other,Rebeccaton,3.2,6.5,98,1,0.0,4,...,0.2,51,13,2.4,0.2,2.4,Social Media,9,5.9,6.2
5998,Barbara Hinton,29,Female,Ramirezmouth,6.7,7.5,67,3,0.2,3,...,1.6,125,17,1.7,2.6,1.5,Browsing,4,6.1,10.0
5999,Curtis Johnson,31,Male,Lake Alexander,3.5,6.9,79,4,2.1,4,...,0.6,117,8,0.0,2.3,0.1,Education,7,5.1,6.3

In [ ]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Name                       6000 non-null   object
 1   Age                        6000 non-null   int64
 2   Gender                     6000 non-null   object
 3   Location                   6000 non-null   object
 4   Daily_Usage_Hours          6000 non-null   float64
 5   Sleep_Hours                6000 non-null   float64
 6   Interllectual_Performance  6000 non-null   int64
 7   Social_Interactions        6000 non-null   int64
 8   Exercise_Hours             6000 non-null   float64
 9   Anxiety_Level              6000 non-null   int64
 10  Depression_Level           6000 non-null   int64
 11  Self_Esteem                6000 non-null   int64
 12  Screen_Time_Before_Bed     6000 non-null   float64
 13  Phone_Checks_Per_Day       6000 non-null   int64
 14  Apps_Used_Daily            6000 non-null   int64
 15  Time_on_Social_Media       6000 non-null   float64
 16  Time_on_Gaming             6000 non-null   float64
 17  Time_on_Education          6000 non-null   float64
 18  Phone_Usage_Purpose        6000 non-null   object
 19  Family_Communication       6000 non-null   int64
 20  Weekend_Usage_Hours        6000 non-null   float64
 21  Addiction_Level            6000 non-null   float64
dtypes: float64(9), int64(9), object(4)
memory usage: 1.0+ MB

In [ ]:
d.duplicated().sum()

np.int64(32)

In [ ]:
d.drop_duplicates(inplace = True)

In [ ]:
d.duplicated().sum()

np.int64(0)

In [ ]:
d.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5968 entries, 0 to 5999
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Name                       5968 non-null   object
 1   Age                        5968 non-null   int64
 2   Gender                     5968 non-null   object
 3   Location                   5968 non-null   object
 4   Daily_Usage_Hours          5968 non-null   float64
 5   Sleep_Hours                5968 non-null   float64
 6   Interllectual_Performance  5968 non-null   int64
 7   Social_Interactions        5968 non-null   int64
 8   Exercise_Hours             5968 non-null   float64
 9   Anxiety_Level              5968 non-null   int64
 10  Depression_Level           5968 non-null   int64
 11  Self_Esteem                5968 non-null   int64
 12  Screen_Time_Before_Bed     5968 non-null   float64
 13  Phone_Checks_Per_Day       5968 non-null   int64
 14  Apps_Used_Daily            5968 non-null   int64
 15  Time_on_Social_Media       5968 non-null   float64
 16  Time_on_Gaming             5968 non-null   float64
 17  Time_on_Education          5968 non-null   float64
 18  Phone_Usage_Purpose        5968 non-null   object
 19  Family_Communication       5968 non-null   int64
 20  Weekend_Usage_Hours        5968 non-null   float64
 21  Addiction_Level            5968 non-null   float64
dtypes: float64(9), int64(9), object(4)
memory usage: 1.0+ MB

In [ ]:
d.drop(columns = ['Name','Location'],inplace = True)

In [ ]:
d.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5968 entries, 0 to 5999
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        5968 non-null   int64
 1   Gender                     5968 non-null   object
 2   Daily_Usage_Hours          5968 non-null   float64
 3   Sleep_Hours                5968 non-null   float64
 4   Interllectual_Performance  5968 non-null   int64
 5   Social_Interactions        5968 non-null   int64
 6   Exercise_Hours             5968 non-null   float64
 7   Anxiety_Level              5968 non-null   int64
 8   Depression_Level           5968 non-null   int64
 9   Self_Esteem                5968 non-null   int64
 10  Screen_Time_Before_Bed     5968 non-null   float64
 11  Phone_Checks_Per_Day       5968 non-null   int64
 12  Apps_Used_Daily            5968 non-null   int64
 13  Time_on_Social_Media       5968 non-null   float64
 14  Time_on_Gaming             5968 non-null   float64
 15  Time_on_Education          5968 non-null   float64
 16  Phone_Usage_Purpose        5968 non-null   object
 17  Family_Communication       5968 non-null   int64
 18  Weekend_Usage_Hours        5968 non-null   float64
 19  Addiction_Level            5968 non-null   float64
dtypes: float64(9), int64(9), object(2)
memory usage: 979.1+ KB

In [ ]:
# Target variable
y = d['Addiction_Level']
# Input variable
X = d.drop(columns = 'Addiction_Level')

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4774, 19)
(1194, 19)
(4774,)
(1194,)

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4774 entries, 4550 to 860
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        4774 non-null   int64
 1   Gender                     4774 non-null   object
 2   Daily_Usage_Hours          4774 non-null   float64
 3   Sleep_Hours                4774 non-null   float64
 4   Interllectual_Performance  4774 non-null   int64
 5   Social_Interactions        4774 non-null   int64
 6   Exercise_Hours             4774 non-null   float64
 7   Anxiety_Level              4774 non-null   int64
 8   Depression_Level           4774 non-null   int64
 9   Self_Esteem                4774 non-null   int64
 10  Screen_Time_Before_Bed     4774 non-null   float64
 11  Phone_Checks_Per_Day       4774 non-null   int64
 12  Apps_Used_Daily            4774 non-null   int64
 13  Time_on_Social_Media       4774 non-null   float64
 14  Time_on_Gaming             4774 non-null   float64
 15  Time_on_Education          4774 non-null   float64
 16  Phone_Usage_Purpose        4774 non-null   object
 17  Family_Communication       4774 non-null   int64
 18  Weekend_Usage_Hours        4774 non-null   float64
dtypes: float64(8), int64(9), object(2)
memory usage: 745.9+ KB

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, RobustScaler
transformer = ColumnTransformer(transformers = [('t1',OrdinalEncoder(),['Gender','Phone_Usage_Purpose']),
                                                ('t2',RobustScaler(),['Age','Daily_Usage_Hours','Sleep_Hours','Interllectual_Performance',
                                                                      'Social_Interactions','Exercise_Hours','Anxiety_Level',
                                                                      'Depression_Level','Self_Esteem','Screen_Time_Before_Bed',
                                                                      'Phone_Checks_Per_Day','Apps_Used_Daily','Time_on_Social_Media',
                                                                      'Time_on_Gaming','Time_on_Education','Family_Communication','Weekend_Usage_Hours'])])
X_train_trans = transformer.fit_transform(X_train)
X_test_trans = transformer.transform(X_test)

In [ ]:
col = ['Gender','Phone_Usage_Purpose','Age',
              'Daily_Usage_Hours','Sleep_Hours','Interllectual_Performance',
              'Social_Interactions','Exercise_Hours','Anxiety_Level',
              'Depression_Level','Self_Esteem','Screen_Time_Before_Bed',
              'Phone_Checks_Per_Day','Apps_Used_Daily','Time_on_Social_Media',
              'Time_on_Gaming','Time_on_Education','Family_Communication','Weekend_Usage_Hours']

In [ ]:
# from sklearn.preprocessing import RobustScaler
# rs = RobustScaler()
# X_train_trans = rs.fit_transform(X_train)
# X_test_trans = rs.transform(X_test)

In [ ]:
X_train_trans = pd.DataFrame(X_train_trans,columns = col )
X_train_trans.head()

,Gender,Phone_Usage_Purpose,Age,Daily_Usage_Hours,Sleep_Hours,Interllectual_Performance,Social_Interactions,Exercise_Hours,Anxiety_Level,Depression_Level,Self_Esteem,Screen_Time_Before_Bed,Phone_Checks_Per_Day,Apps_Used_Daily,Time_on_Social_Media,Time_on_Gaming,Time_on_Education,Family_Communication,Weekend_Usage_Hours
0,1.0,1.0,0.052632,0.925926,-1.00,0.576923,-0.666667,0.8,0.4,0.4,-0.6,0.571429,-0.250000,0.750,-1.000000,-1.071429,-0.4,0.6,0.464286
1,1.0,4.0,0.000000,-0.074074,0.80,-0.730769,0.500000,0.5,-1.0,-0.8,-0.8,0.428571,-0.968750,0.500,-0.357143,-1.000000,1.5,-0.6,0.892857
2,0.0,0.0,1.868421,-0.111111,-0.35,-0.923077,0.500000,0.3,-0.8,0.8,0.2,-1.000000,-0.343750,-0.375,1.142857,-0.214286,0.3,0.2,-0.357143
3,2.0,3.0,0.842105,0.814815,0.95,-0.730769,0.500000,-0.8,-1.0,0.6,0.6,0.714286,-0.156250,0.125,-0.214286,1.071429,-0.9,0.6,0.000000
4,1.0,2.0,-0.078947,1.037037,0.15,0.884615,-0.500000,0.4,0.8,0.8,-0.6,-0.285714,-0.671875,0.625,-1.000000,-0.500000,0.8,0.6,0.000000

In [ ]:
X_test_trans = pd.DataFrame(X_test_trans,columns = col)
X_test_trans.head()

,Gender,Phone_Usage_Purpose,Age,Daily_Usage_Hours,Sleep_Hours,Interllectual_Performance,Social_Interactions,Exercise_Hours,Anxiety_Level,Depression_Level,Self_Esteem,Screen_Time_Before_Bed,Phone_Checks_Per_Day,Apps_Used_Daily,Time_on_Social_Media,Time_on_Gaming,Time_on_Education,Family_Communication,Weekend_Usage_Hours
0,2.0,1.0,0.000000,-0.777778,-0.15,-0.961538,-0.666667,-0.4,-0.8,0.6,0.6,0.714286,-0.406250,-1.00,0.357143,-0.285714,-0.2,0.2,-0.285714
1,0.0,2.0,-0.105263,-0.037037,0.15,-0.653846,0.833333,-1.0,0.8,-0.2,-0.6,1.000000,-0.156250,0.75,-0.857143,0.500000,0.3,-0.6,1.642857
2,1.0,2.0,0.026316,-0.037037,-0.20,-0.153846,0.500000,0.8,-0.8,0.0,0.4,0.000000,-0.281250,-0.25,-1.071429,-1.071429,0.2,0.6,-0.357143
3,2.0,3.0,1.526316,-0.111111,-0.30,-0.730769,-0.166667,-0.3,0.0,-0.2,0.4,-0.285714,-0.140625,-1.00,-0.285714,0.714286,-0.1,0.0,-1.428571
4,1.0,0.0,1.894737,-0.666667,-0.15,0.423077,0.666667,0.0,0.0,-0.8,-0.4,0.428571,0.750000,0.75,-0.642857,0.428571,-0.8,0.2,-0.107143

**1. KNN Regression Model:**

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
knn_model = KNeighborsRegressor()
knn_model.fit(X_train_trans,y_train)

KNeighborsRegressor()

In [ ]:
y_pred = knn_model.predict(X_test_trans)

In [ ]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error
print('R2_Score:',r2_score(y_pred,y_test))
print('MAE:',mean_absolute_error(y_pred,y_test))
print('MSE:',mean_squared_error(y_pred,y_test))
print('RMSE:',root_mean_squared_error(y_pred,y_test))

R2_Score: 0.35254733792279647
MAE: 0.5822613065326634
MSE: 0.7841289782244556
RMSE: 0.8855105748800833

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsRegressor
pipe = Pipeline([
    ("preprocessor", transformer),
    ("model", KNeighborsRegressor(
        n_neighbors=5,
        metric='minkowski',
        p=2  # Euclidean distance
    ))
])
pipe.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('t1', OrdinalEncoder(),
                                                  ['Gender',
                                                   'Phone_Usage_Purpose']),
                                                 ('t2', RobustScaler(),
                                                  ['Age', 'Daily_Usage_Hours',
                                                   'Sleep_Hours',
                                                   'Interllectual_Performance',
                                                   'Social_Interactions',
                                                   'Exercise_Hours',
                                                   'Anxiety_Level',
                                                   'Depression_Level',
                                                   'Self_Esteem',
                                                   'Screen_Time_Before_Bed',
                                                   'Phone_Checks_Per_Day',
                                                   'Apps_Used_Daily',
                                                   'Time_on_Social_Media',
                                                   'Time_on_Gaming',
                                                   'Time_on_Education',
                                                   'Family_Communication',
                                                   'Weekend_Usage_Hours'])])),
                ('model', KNeighborsRegressor())])

In [ ]:
y_pred = pipe.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.7055422817466179

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.neighbors import KNeighborsRegressor
param_grid = {
    "model__n_neighbors": [3, 5, 7, 9, 11],
    "model__weights": ["uniform", "distance"],
    "model__metric": ["euclidean", "manhattan"]
}

rscv = RandomizedSearchCV(
    pipe,
    param_grid,
    cv=5,
    scoring="r2"
)

rscv.fit(X_train, y_train)

print("Best Parameters:", rscv.best_params_)
print("Best Accuracy:", rscv.best_score_)

Best Parameters: {'model__weights': 'distance', 'model__n_neighbors': 7, 'model__metric': 'manhattan'}
Best Accuracy: 0.7751079090189433

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4774 entries, 4550 to 860
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        4774 non-null   int64
 1   Sleep_Hours                4774 non-null   float64
 2   Interllectual_Performance  4774 non-null   int64
 3   Anxiety_Level              4774 non-null   int64
 4   Depression_Level           4774 non-null   int64
 5   Apps_Used_Daily            4774 non-null   int64
 6   Time_on_Social_Media       4774 non-null   float64
 7   Time_on_Gaming             4774 non-null   float64
 8   Time_on_Education          4774 non-null   float64
 9   Weekend_Usage_Hours        4774 non-null   float64
dtypes: float64(5), int64(5)
memory usage: 410.3 KB

**2. Naive Bayes Model:**

Naive Bayes is deals with only 'Classification'.

**3. Decision Tree Classification Model:**

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dt_model = DecisionTreeRegressor()
dt_model.fit(X_train_trans,y_train)

DecisionTreeRegressor()

In [ ]:
y_pred = dt_model.predict(X_test_trans)

In [ ]:
r2_score(y_test,y_pred)

0.9085066009964311

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeRegressor
pipe_dt = Pipeline([
    ("preprocessor", transformer),
    ("model", DecisionTreeRegressor(
        criterion = 'squared_error',
        max_depth = 5,
        random_state = 42
    ))
])
pipe_dt.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('t1', OrdinalEncoder(),
                                                  ['Gender',
                                                   'Phone_Usage_Purpose']),
                                                 ('t2', RobustScaler(),
                                                  ['Age', 'Daily_Usage_Hours',
                                                   'Sleep_Hours',
                                                   'Interllectual_Performance',
                                                   'Social_Interactions',
                                                   'Exercise_Hours',
                                                   'Anxiety_Level',
                                                   'Depression_Level',
                                                   'Self_Esteem',
                                                   'Screen_Time_Before_Bed',
                                                   'Phone_Checks_Per_Day',
                                                   'Apps_Used_Daily',
                                                   'Time_on_Social_Media',
                                                   'Time_on_Gaming',
                                                   'Time_on_Education',
                                                   'Family_Communication',
                                                   'Weekend_Usage_Hours'])])),
                ('model', DecisionTreeRegressor(max_depth=5, random_state=42))])

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.neighbors import KNeighborsRegressor
param_grid = {
    "model__max_depth": [3, 5, 10, 15, None],
    "model__min_samples_split": [2, 5, 10],
    "model__min_samples_leaf": [1, 2, 4],
    "model__criterion": ["squared_error", "absolute_error", "friedman_mse"]
}

rscv = RandomizedSearchCV(
    pipe_dt,
    param_distributions = param_grid,
    n_iter = 10,
    cv=5,
    scoring="r2",
    random_state = 42
)

rscv.fit(X_train, y_train)

print("Best Parameters:", rscv.best_params_)
print("Best Accuracy:", rscv.best_score_)

Best Parameters: {'model__min_samples_split': 5, 'model__min_samples_leaf': 1, 'model__max_depth': 10, 'model__criterion': 'squared_error'}
Best Accuracy: 0.849012135780448

/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_validation.py:489: FitFailedWarning:
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/sklearn/base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.13/dist-packages/sklearn/pipeline.py", line 649, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/sklearn/base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/dist-packages/sklearn/base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'poisson', 'squared_error', 'absolute_error'}. Got 'friedman_mse' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_search.py:1234: UserWarning: One or more of the test scores are non-finite: [       nan 0.69285771        nan 0.84901214 0.84821643 0.52974153
 0.63363215        nan        nan        nan]
  warnings.warn(

In [ ]:
import sklearn
print(sklearn.__version__)

1.9.0

In [ ]:
import pickle
import joblib

In [ ]:
# serialization
with open("model1.pkl","wb") as f:
  pickle.dump(pipe_dt,f)

In [ ]:
joblib.dump(rscv,'dt_model.pkl')

['dt_model.pkl']

In [ ]:
import joblib
model = joblib.load("/content/model.pkl")

In [ ]:
joblib.dump(X_train.columns, "columns.pkl")

['columns.pkl']

In [ ]:
X_train.columns

Index(['Age', 'Gender', 'Daily_Usage_Hours', 'Sleep_Hours',
       'Interllectual_Performance', 'Social_Interactions', 'Exercise_Hours',
       'Anxiety_Level', 'Depression_Level', 'Self_Esteem',
       'Screen_Time_Before_Bed', 'Phone_Checks_Per_Day', 'Apps_Used_Daily',
       'Time_on_Social_Media', 'Time_on_Gaming', 'Time_on_Education',
       'Phone_Usage_Purpose', 'Family_Communication', 'Weekend_Usage_Hours'],
      dtype='object')

In [ ]:
import joblib
# joblib.dump(pipe_dt, "model.pkl")
model = joblib.load("model.pkl")

In [ ]:
# During training
joblib.dump(model.estimator_, "model_only.pkl")
# joblib.dump(transformer, "preprocessor.pkl")

AttributeError: 'Pipeline' object has no attribute 'estimator_'

4. **Linear Regression:**

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
pipe_lr = Pipeline([
    ("preprocessor", transformer),
    ("model", Ridge())
])
pipe_lr.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('t1', OrdinalEncoder(),
                                                  ['Gender',
                                                   'Phone_Usage_Purpose']),
                                                 ('t2', RobustScaler(),
                                                  ['Age', 'Daily_Usage_Hours',
                                                   'Sleep_Hours',
                                                   'Interllectual_Performance',
                                                   'Social_Interactions',
                                                   'Exercise_Hours',
                                                   'Anxiety_Level',
                                                   'Depression_Level',
                                                   'Self_Esteem',
                                                   'Screen_Time_Before_Bed',
                                                   'Phone_Checks_Per_Day',
                                                   'Apps_Used_Daily',
                                                   'Time_on_Social_Media',
                                                   'Time_on_Gaming',
                                                   'Time_on_Education',
                                                   'Family_Communication',
                                                   'Weekend_Usage_Hours'])])),
                ('model', Ridge())])

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.neighbors import KNeighborsRegressor
param_grid = {
    "model__alpha": [0.01, 0.1, 1.0, 10.0, 100.0],
    "model__fit_intercept": [True, False]
}

logr = RandomizedSearchCV(
    estimator = pipe_lr,
    param_distributions = param_grid,
    n_iter = 10,
    cv=5,
    scoring="r2",
    random_state = 42
)

logr.fit(X_train, y_train)

print("Best Parameters:", logr.best_params_)
print("Best Accuracy:", logr.best_score_)

Best Parameters: {'model__fit_intercept': True, 'model__alpha': 10.0}
Best Accuracy: 0.7315363288273715

5. **Logistic Regression:**

6. **SVC**

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.svm import SVR
pipe_svr = Pipeline([
    ("preprocessor", transformer),
    ("model", SVR())
])
pipe_svr.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('t1', OrdinalEncoder(),
                                                  ['Gender',
                                                   'Phone_Usage_Purpose']),
                                                 ('t2', RobustScaler(),
                                                  ['Age', 'Daily_Usage_Hours',
                                                   'Sleep_Hours',
                                                   'Interllectual_Performance',
                                                   'Social_Interactions',
                                                   'Exercise_Hours',
                                                   'Anxiety_Level',
                                                   'Depression_Level',
                                                   'Self_Esteem',
                                                   'Screen_Time_Before_Bed',
                                                   'Phone_Checks_Per_Day',
                                                   'Apps_Used_Daily',
                                                   'Time_on_Social_Media',
                                                   'Time_on_Gaming',
                                                   'Time_on_Education',
                                                   'Family_Communication',
                                                   'Weekend_Usage_Hours'])])),
                ('model', SVR())])

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

param_grid = {
    'model__C': [0.1, 1, 10],            # Replace classifier__ with model__
    'model__kernel': ['rbf', 'linear']    # Replace classifier__ with model__
}

svrR = RandomizedSearchCV(
    estimator=pipe_svr,
    param_distributions=param_grid,
    cv=5,
    scoring="r2",
    verbose=2
)

svrR.fit(X_train, y_train)

print("Best Params:", svrR.best_params_)
print("Best Score:", svrR.best_score_)

/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END ....................model__C=0.1, model__kernel=rbf; total time=   2.2s
[CV] END ....................model__C=0.1, model__kernel=rbf; total time=   1.5s
[CV] END ....................model__C=0.1, model__kernel=rbf; total time=   0.9s
[CV] END ....................model__C=0.1, model__kernel=rbf; total time=   0.9s
[CV] END ....................model__C=0.1, model__kernel=rbf; total time=   0.9s
[CV] END .................model__C=0.1, model__kernel=linear; total time=   0.8s
[CV] END .................model__C=0.1, model__kernel=linear; total time=   0.8s
[CV] END .................model__C=0.1, model__kernel=linear; total time=   0.8s
[CV] END .................model__C=0.1, model__kernel=linear; total time=   0.8s
[CV] END .................model__C=0.1, model__kernel=linear; total time=   0.7s
[CV] END ......................model__C=1, model__kernel=rbf; total time=   1.1s
[CV] END ......................model__C=1, model__kernel=rbf; total time=   1.8s
[CV] END ......................model__C=1, model__kernel=rbf; total time=   1.9s
[CV] END ......................model__C=1, model__kernel=rbf; total time=   1.7s
[CV] END ......................model__C=1, model__kernel=rbf; total time=   1.1s
[CV] END ...................model__C=1, model__kernel=linear; total time=   1.7s
[CV] END ...................model__C=1, model__kernel=linear; total time=   1.7s
[CV] END ...................model__C=1, model__kernel=linear; total time=   2.3s
[CV] END ...................model__C=1, model__kernel=linear; total time=   1.8s
[CV] END ...................model__C=1, model__kernel=linear; total time=   2.2s
[CV] END .....................model__C=10, model__kernel=rbf; total time=   5.4s
[CV] END .....................model__C=10, model__kernel=rbf; total time=   3.6s
[CV] END .....................model__C=10, model__kernel=rbf; total time=   4.0s
[CV] END .....................model__C=10, model__kernel=rbf; total time=   5.8s
[CV] END .....................model__C=10, model__kernel=rbf; total time=   4.0s
[CV] END ..................model__C=10, model__kernel=linear; total time=  11.3s
[CV] END ..................model__C=10, model__kernel=linear; total time=   9.2s
[CV] END ..................model__C=10, model__kernel=linear; total time=  11.1s
[CV] END ..................model__C=10, model__kernel=linear; total time=  11.3s
[CV] END ..................model__C=10, model__kernel=linear; total time=  10.0s
Best Params: {'model__kernel': 'rbf', 'model__C': 10}
Best Score: 0.979218975519669

In [ ]:
import joblib
joblib.dump(svrR,'svrmodel.pkl')

['svrmodel.pkl']

In [ ]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.pipeline import Pipeline

# 1. Pipeline Definition & Initial Fit
pipe_ada = Pipeline([
    ("preprocessor", transformer),
    ("model", AdaBoostRegressor(random_state=42))
])
pipe_ada.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('t1', OrdinalEncoder(),
                                                  ['Gender',
                                                   'Phone_Usage_Purpose']),
                                                 ('t2', RobustScaler(),
                                                  ['Age', 'Daily_Usage_Hours',
                                                   'Sleep_Hours',
                                                   'Interllectual_Performance',
                                                   'Social_Interactions',
                                                   'Exercise_Hours',
                                                   'Anxiety_Level',
                                                   'Depression_Level',
                                                   'Self_Esteem',
                                                   'Screen_Time_Before_Bed',
                                                   'Phone_Checks_Per_Day',
                                                   'Apps_Used_Daily',
                                                   'Time_on_Social_Media',
                                                   'Time_on_Gaming',
                                                   'Time_on_Education',
                                                   'Family_Communication',
                                                   'Weekend_Usage_Hours'])])),
                ('model', AdaBoostRegressor(random_state=42))])

In [ ]:
# 2. Hyperparameter Tuning
param_grid_ada = {
    "model__n_estimators": [50, 100, 200, 300],
    "model__learning_rate": [0.01, 0.05, 0.1, 0.5, 1.0],
    "model__loss": ["linear", "square", "exponential"]
}

rscv_ada = RandomizedSearchCV(
    estimator=pipe_ada,
    param_distributions=param_grid_ada,
    cv=5,
    scoring="r2",
    n_iter=10,
    random_state=42
)
rscv_ada.fit(X_train, y_train)
print('Best Parameters:', rscv_ada.best_params_)
print('Best R2 Score:', rscv_ada.best_score_)

Best Parameters: {'model__n_estimators': 200, 'model__loss': 'square', 'model__learning_rate': 1.0}
Best R2 Score: 0.8000455353912747

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.pipeline import Pipeline

# 1. Pipeline Definition & Initial Fit
pipe_gb = Pipeline([
    ("preprocessor", transformer),
    ("model", GradientBoostingRegressor(random_state=42))
])
pipe_gb.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('t1', OrdinalEncoder(),
                                                  ['Gender',
                                                   'Phone_Usage_Purpose']),
                                                 ('t2', RobustScaler(),
                                                  ['Age', 'Daily_Usage_Hours',
                                                   'Sleep_Hours',
                                                   'Interllectual_Performance',
                                                   'Social_Interactions',
                                                   'Exercise_Hours',
                                                   'Anxiety_Level',
                                                   'Depression_Level',
                                                   'Self_Esteem',
                                                   'Screen_Time_Before_Bed',
                                                   'Phone_Checks_Per_Day',
                                                   'Apps_Used_Daily',
                                                   'Time_on_Social_Media',
                                                   'Time_on_Gaming',
                                                   'Time_on_Education',
                                                   'Family_Communication',
                                                   'Weekend_Usage_Hours'])])),
                ('model', GradientBoostingRegressor(random_state=42))])

In [ ]:
# 2. Hyperparameter Tuning
param_grid_gb = {
    "model__n_estimators": [50, 100, 200, 300],
    "model__learning_rate": [0.01, 0.05, 0.1, 0.2],
    "model__max_depth": [3, 5, 7, 10],
    "model__min_samples_split": [2, 5, 10],
    "model__min_samples_leaf": [1, 2, 4],
    "model__subsample": [0.6, 0.8, 1.0]
}

rscv_gb = RandomizedSearchCV(
    estimator=pipe_gb,
    param_distributions=param_grid_gb,
    cv=5,
    scoring="r2",
    n_iter=10,
    random_state=42
)
rscv_gb.fit(X_train, y_train)
print('Best Parameters:', rscv_gb.best_params_)
print('Best R2 Score:', rscv_gb.best_score_)

Best Parameters: {'model__subsample': 0.8, 'model__n_estimators': 200, 'model__min_samples_split': 5, 'model__min_samples_leaf': 2, 'model__max_depth': 5, 'model__learning_rate': 0.2}
Best R2 Score: 0.9743875784517989

In [ ]:
sklearn.__version__

'1.9.0'

In [ ]:
import joblib
joblib.dump(rscv_gb,'gradient_boost_model.pkl')

['gradient_boost_model.pkl']

In [ ]:
from xgboost import XGBRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.pipeline import Pipeline

# 1. Pipeline Definition & Initial Fit
pipe_xgb = Pipeline([
    ("preprocessor", transformer),
    ("model", XGBRegressor(random_state=42))
])
pipe_xgb.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('t1', OrdinalEncoder(),
                                                  ['Gender',
                                                   'Phone_Usage_Purpose']),
                                                 ('t2', RobustScaler(),
                                                  ['Age', 'Daily_Usage_Hours',
                                                   'Sleep_Hours',
                                                   'Interllectual_Performance',
                                                   'Social_Interactions',
                                                   'Exercise_Hours',
                                                   'Anxiety_Level',
                                                   'Depression_Level',
                                                   'Self_Esteem',
                                                   'Screen_Time_Before_Bed',
                                                   'Phone_Checks_Per_Day',
                                                   'Ap...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [ ]:
# 2. Hyperparameter Tuning
param_grid_xgb = {
    "model__n_estimators": [50, 100, 200, 300],
    "model__learning_rate": [0.01, 0.05, 0.1, 0.2],
    "model__max_depth": [3, 5, 7, 10],
    "model__subsample": [0.6, 0.8, 1.0],
    "model__colsample_bytree": [0.6, 0.8, 1.0],
    "model__gamma": [0, 0.1, 0.2, 0.3]
}

rscv_xgb = RandomizedSearchCV(
    estimator=pipe_xgb,
    param_distributions=param_grid_xgb,
    cv=5,
    scoring="r2",
    n_iter=10,
    random_state=42
)
rscv_xgb.fit(X_train, y_train)
print('Best Parameters:', rscv_xgb.best_params_)
print('Best R2 Score:', rscv_xgb.best_score_)

Best Parameters: {'model__subsample': 0.6, 'model__n_estimators': 200, 'model__max_depth': 3, 'model__learning_rate': 0.1, 'model__gamma': 0, 'model__colsample_bytree': 1.0}
Best R2 Score: 0.9515481633824772

| Model           | Best Score |
|---------------------|------|
| KNN                 | 0.775107 |
| Decision Tree   | 0.849012  |
| Linear Regression         | 0.731536  |
| AdaBoost                    | 0.80004   |
|Gradient Boosting | 0.974387|
|XGB Boost | 0.951548|

so the Best model is **Gradient Boosting** which the score is **0.974387**

In [ ]:
import sklearn
sklearn.__version__

'1.6.1'